//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.04 at 04:25:51 PM EEST 
//


package ua.selftaught.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.selftaught.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.selftaught.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.Orders }
     * 
     */
    public Root.Orders createRootOrders() {
        return new Root.Orders();
    }

    /**
     * Create an instance of {@link Root.Orders.Order }
     * 
     */
    public Root.Orders.Order createRootOrdersOrder() {
        return new Root.Orders.Order();
    }

    /**
     * Create an instance of {@link Root.Customers }
     * 
     */
    public Root.Customers createRootCustomers() {
        return new Root.Customers();
    }

    /**
     * Create an instance of {@link Root.Customers.Customer }
     * 
     */
    public Root.Customers.Customer createRootCustomersCustomer() {
        return new Root.Customers.Customer();
    }

    /**
     * Create an instance of {@link Root.Orders.Order.ShipInfo }
     * 
     */
    public Root.Orders.Order.ShipInfo createRootOrdersOrderShipInfo() {
        return new Root.Orders.Order.ShipInfo();
    }

    /**
     * Create an instance of {@link Root.Customers.Customer.FullAddress }
     * 
     */
    public Root.Customers.Customer.FullAddress createRootCustomersCustomerFullAddress() {
        return new Root.Customers.Customer.FullAddress();
    }

}
